# Generated by Django 3.2.5 on 2021-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALAA_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_proposer', models.CharField(max_length=200)),
                ('details_proposer', models.TextField()),
                ('proposer_address', models.TextField()),
                ('proposer_mob', models.CharField(max_length=16)),
                ('proposer_email', models.CharField(max_length=63)),
                ('name_nominee', models.CharField(max_length=63)),
                ('nominee_father_name', models.CharField(max_length=63)),
                ('dob', models.CharField(max_length=63)),
                ('degree', models.CharField(max_length=63)),
                ('dept', models.CharField(max_length=63)),
                ('yop', models.CharField(max_length=63)),
                ('rollno', models.CharField(max_length=63)),
                ('otherquali', models.CharField(max_length=255)),
                ('ppo', models.CharField(max_length=255)),
                ('nominee_address', models.CharField(max_length=255)),
                ('nominee_mob', models.CharField(max_length=16)),
                ('nomionee_email', models.CharField(max_length=63)),
                ('profile_pic', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('accom', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
