# Generated by Django 3.2.5 on 2021-07-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(max_length=7)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mob', models.CharField(max_length=63)),
                ('alumini', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('something', models.BooleanField(default=False)),
                ('yop', models.CharField(max_length=63)),
                ('degree', models.CharField(max_length=63)),
                ('dept', models.CharField(max_length=63)),
                ('specialization', models.CharField(max_length=63)),
                ('award', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=255)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
