# Generated by Django 3.2.5 on 2021-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_idcount_proposer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposer',
            name='app_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proposer',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
