# Generated by Django 3.2.5 on 2021-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20210718_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposer',
            name='address',
            field=models.TextField(max_length=355),
        ),
        migrations.AlterField(
            model_name='proposer',
            name='award',
            field=models.CharField(max_length=255),
        ),
    ]
