# Generated by Django 3.2.5 on 2021-07-19 07:17

import django.core.validators
from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210718_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award_From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('award', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['jpeg'])])),
                ('father_name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('yop', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('mob', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('ppo', models.CharField(max_length=255)),
                ('destinctions', models.TextField(blank=True)),
                ('destinctions_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('higher_eduction', models.TextField(blank=True)),
                ('professional_exp', models.TextField(blank=True)),
                ('prof_contri_papers', models.CharField(max_length=10)),
                ('prof_contri_papers_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_patents', models.CharField(max_length=10)),
                ('prof_contri_patents_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_membership', models.CharField(max_length=10)),
                ('prof_contri_membership_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_books', models.CharField(max_length=10)),
                ('prof_contri_books_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_others', models.CharField(max_length=10)),
                ('prof_contri_others_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_hon_award', models.TextField(blank=True)),
                ('prof_hon_award_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('nom_accom_con', models.TextField(blank=True)),
                ('nom_accom_con_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ls1_details', models.TextField(blank=True)),
                ('ls1_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ls2_details', models.TextField(blank=True)),
                ('ls2_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('resume', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('additional_materials', models.TextField(blank=True)),
                ('add_file', models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='proposer',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
