# Generated by Django 3.2.5 on 2021-07-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210719_0717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Award_From',
            new_name='Award_Formm',
        ),
        migrations.RenameField(
            model_name='award_formm',
            old_name='destinctions',
            new_name='distinctions',
        ),
        migrations.RenameField(
            model_name='award_formm',
            old_name='destinctions_file',
            new_name='distinctions_file',
        ),
    ]
