# Generated by Django 3.2.5 on 2021-07-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210719_0817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Award_Formm',
            new_name='Award_Form',
        ),
    ]
