# Generated by Django 3.2.5 on 2021-07-20 02:40

import django.core.validators
from django.db import migrations, models
import forms.path


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_rename_award_formm_award_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award_Formm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('award', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=forms.path.profile_pic_path, validators=[django.core.validators.FileExtensionValidator(['jpeg'])])),
                ('father_name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('yop', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('mob', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('ppo', models.CharField(max_length=255)),
                ('distinctions', models.TextField(blank=True)),
                ('distinctions_file', models.FileField(blank=True, null=True, upload_to=forms.path.distinction_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('higher_eduction', models.TextField(blank=True)),
                ('professional_exp', models.TextField(blank=True)),
                ('prof_contri_papers', models.CharField(max_length=10)),
                ('prof_contri_papers_file', models.FileField(blank=True, null=True, upload_to=forms.path.prof_contri_papers_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_patents', models.CharField(max_length=10)),
                ('prof_contri_patents_file', models.FileField(blank=True, null=True, upload_to=forms.path.prof_contri_patents_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_membership', models.CharField(max_length=10)),
                ('prof_contri_membership_file', models.FileField(blank=True, null=True, upload_to=forms.path.prof_contri_membership_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_books', models.CharField(max_length=10)),
                ('prof_contri_books_file', models.FileField(blank=True, null=True, upload_to=forms.path.prof_contri_books_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_contri_others', models.CharField(max_length=10)),
                ('prof_contri_others_file', models.FileField(blank=True, null=True, upload_to=forms.path.prof_contri_others_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('prof_hon_award', models.TextField(blank=True)),
                ('prof_hon_award_file', models.FileField(blank=True, null=True, upload_to=forms.path.prof_hon_award_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('nom_accom_con', models.TextField(blank=True)),
                ('nom_accom_con_file', models.FileField(blank=True, null=True, upload_to=forms.path.nom_accom_con_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ls1_details', models.TextField(blank=True)),
                ('ls1_file', models.FileField(blank=True, null=True, upload_to=forms.path.ls1_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ls2_details', models.TextField(blank=True)),
                ('ls2_file', models.FileField(blank=True, null=True, upload_to=forms.path.ls2_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('resume', models.FileField(blank=True, null=True, upload_to=forms.path.resume_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('additional_materials', models.TextField(blank=True)),
                ('add_file', models.FileField(blank=True, null=True, upload_to=forms.path.add_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Award_Form',
        ),
    ]
