# Generated by Django 3.2.5 on 2021-07-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20210720_0240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Award_Formm',
            new_name='Award_Form',
        ),
    ]
