# Generated by Django 3.2.5 on 2021-07-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_rename_award_formm_award_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposer',
            name='ppo',
            field=models.CharField(default='Alumni', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
