# Generated by Django 3.2.5 on 2021-07-28 07:40

import django.core.validators
from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20210723_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award_form',
            name='distinctions_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='ls1_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='ls2_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='nom_accom_con_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='prof_contri_books_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='prof_contri_membership_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='prof_contri_others_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='prof_contri_papers_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='prof_contri_patents_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='prof_hon_award_file',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['jpeg'])]),
        ),
        migrations.AlterField(
            model_name='award_form',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
